In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
type(arr)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3], [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a2.ndim

2

In [6]:
a3 = np.array([[[1,2,3],
                [4,5,6]],
               [[7,8,9],
               [10,11,12]],
               [[13,14,15],
                [16,17,18]]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [8]:
a3.ndim

3

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(3, 2, 3)

In [11]:
a3.dtype

dtype('int32')

In [12]:
a3.size

18

In [17]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [20]:
ones = np.ones((2, 3))

In [23]:
ones.dtype, type(ones)

(dtype('float64'), numpy.ndarray)

In [25]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
arange = np.arange(0, 10, 2)
arange

array([0, 2, 4, 6, 8])

In [36]:
np.random.seed(1764)
random = np.random.randint(10, size=(2,4))
random

array([[0, 4, 7, 4],
       [4, 0, 0, 9]])

In [39]:
random = np.random.random(size=(4,3))
random

array([[0.49230798, 0.27859699, 0.12926531],
       [0.55248717, 0.85006993, 0.89561583],
       [0.27526847, 0.42507804, 0.32492422],
       [0.79571465, 0.24117731, 0.98843921]])

In [41]:
rand = np.random.rand(3, 5)
rand

array([[0.52537362, 0.06685838, 0.60730602, 0.94005644, 0.48977612],
       [0.2763443 , 0.97446638, 0.03409531, 0.16666452, 0.85530953],
       [0.92184278, 0.85976695, 0.12729551, 0.92537719, 0.97775071]])

In [42]:
np.unique(rand)

array([0.03409531, 0.06685838, 0.12729551, 0.16666452, 0.2763443 ,
       0.48977612, 0.52537362, 0.60730602, 0.85530953, 0.85976695,
       0.92184278, 0.92537719, 0.94005644, 0.97446638, 0.97775071])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [44]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [45]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 1, 5, 1, 5],
         [9, 3, 1, 4, 3],
         [8, 6, 2, 6, 2],
         [5, 1, 9, 4, 6]],

        [[8, 4, 4, 6, 6],
         [4, 0, 0, 3, 6],
         [2, 8, 0, 5, 1],
         [8, 4, 4, 1, 5]],

        [[8, 4, 6, 5, 1],
         [2, 9, 4, 4, 1],
         [5, 1, 1, 4, 7],
         [9, 1, 1, 9, 7]]],


       [[[6, 8, 1, 8, 7],
         [4, 6, 1, 4, 7],
         [6, 9, 8, 1, 1],
         [5, 2, 3, 3, 9]],

        [[1, 6, 5, 1, 8],
         [5, 1, 6, 5, 4],
         [4, 6, 0, 8, 9],
         [2, 6, 0, 9, 6]],

        [[3, 8, 7, 4, 5],
         [9, 0, 7, 4, 0],
         [9, 2, 6, 7, 7],
         [2, 9, 8, 0, 0]]]])

In [48]:
a4.size, a4.shape, a4.ndim, type(a4), a4.dtype

(120, (2, 3, 4, 5), 4, numpy.ndarray, dtype('int32'))

In [71]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [73]:
a2.shape, a3.shape

((2, 3), (3, 2, 3))

In [77]:
a3 = a3.reshape((2,3,3))

In [80]:
a2*a3.reshape(3,2,3)

array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[  7,  16,  27],
        [ 40,  55,  72]],

       [[ 13,  28,  45],
        [ 64,  85, 108]]])

In [81]:
np.exp(a3)

array([[[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]],

       [[2.20264658e+04, 5.98741417e+04, 1.62754791e+05],
        [4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
        [8.88611052e+06, 2.41549528e+07, 6.56599691e+07]]])

In [82]:
np.log(a3)

array([[[0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947],
        [1.94591015, 2.07944154, 2.19722458]],

       [[2.30258509, 2.39789527, 2.48490665],
        [2.56494936, 2.63905733, 2.7080502 ],
        [2.77258872, 2.83321334, 2.89037176]]])

In [83]:
np.absolute(a3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [84]:
np.min(a3)

1

In [85]:
np.max(a3)

18

In [86]:
np.std(a3)

5.188127472091127

In [8]:
a2*a3

array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[  7,  16,  27],
        [ 40,  55,  72]],

       [[ 13,  28,  45],
        [ 64,  85, 108]]])

In [10]:
a2.shape, a3.shape

((2, 3), (3, 2, 3))

In [13]:
a3*a2.reshape(3, 2, 1)

array([[[  1,   2,   3],
        [  8,  10,  12]],

       [[ 21,  24,  27],
        [ 40,  44,  48]],

       [[ 65,  70,  75],
        [ 96, 102, 108]]])

In [19]:
np.transpose(a3)

array([[[ 1,  7, 13],
        [ 4, 10, 16]],

       [[ 2,  8, 14],
        [ 5, 11, 17]],

       [[ 3,  9, 15],
        [ 6, 12, 18]]])

In [24]:
a3.T.shape

(3, 2, 3)

In [30]:
np.random.default_rng().integers(10, size=(3,4))

array([[4, 1, 5, 4],
       [2, 1, 1, 0],
       [9, 7, 7, 7]], dtype=int64)

In [32]:
np.random.seed(0)
sales_butter = np.random.default_rng().integers(10, size=(5, 3))
sales_butter

array([[7, 5, 3],
       [9, 4, 6],
       [4, 8, 5],
       [0, 9, 3],
       [1, 0, 1]], dtype=int64)

In [47]:
butter = pd.DataFrame(sales_butter, index=["Mon", "Tues", "Wed", "Thurs", "Fri"], columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter

Almond butter  Peanut butter  Cashew butter
Mon                7              5              3
Tues               9              4              6
Wed                4              8              5
Thurs              0              9              3
Fri                1              0              1

In [48]:
price_butter = np.array([10, 8, 12])
price_butter

array([10,  8, 12])

In [49]:
price = pd.DataFrame(price_butter.reshape(1,3), index=["Price"], columns=["Almond butter", "Peanut butter", "Cashew butter"])
price

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [50]:
total = price_butter.dot(sales_butter.T)
total

array([146, 194, 164, 108,  22], dtype=int64)

In [51]:
butter["Total $"] = total

In [52]:
butter

Almond butter  Peanut butter  Cashew butter  Total $
Mon                7              5              3      146
Tues               9              4              6      194
Wed                4              8              5      164
Thurs              0              9              3      108
Fri                1              0              1       22

In [53]:
sales_butter

array([[7, 5, 3],
       [9, 4, 6],
       [4, 8, 5],
       [0, 9, 3],
       [1, 0, 1]], dtype=int64)

In [56]:
np.sort(sales_butter, axis=0)

array([[0, 0, 1],
       [1, 4, 3],
       [4, 5, 3],
       [7, 8, 5],
       [9, 9, 6]], dtype=int64)

In [57]:
np.argsort(sales_butter)

array([[2, 1, 0],
       [1, 2, 0],
       [0, 2, 1],
       [0, 2, 1],
       [1, 0, 2]], dtype=int64)

In [62]:
sales_butter

array([[7, 5, 3],
       [9, 4, 6],
       [4, 8, 5],
       [0, 9, 3],
       [1, 0, 1]], dtype=int64)

In [63]:
np.argmax(sales_butter, axis=1)

array([0, 0, 1, 1, 0], dtype=int64)

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2],
       [3, 1],
       [3, 2],
       [4, 0],
       [4, 2]], dtype=int64)

<img src="panda.png">

In [70]:
from matplotlib.image import imread
img = imread("panda.png", format=".png")

In [72]:
img.ndim, img.shape, img.size, img.dtype, type()

(3, (2330, 3500, 3), 24465000, dtype('float32'))

In [78]:
import matplotlib.pyplot as plt