In [113]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
arr = np.array(range(5))

In [8]:
arr

array([0, 1, 2, 3, 4])

In [9]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8]])
arr3 = np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])

In [10]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
arr2.shape

(2, 4)

In [13]:
arr3.shape

(2, 3, 3)

In [14]:
arr3.ndim

3

In [15]:
arr3.dtype

dtype('int32')

In [16]:
arr3.size

18

In [17]:
type(arr3)

numpy.ndarray

In [24]:
df = pd.DataFrame(arr2)

In [23]:
df

ali  ahmad  joseph  you
0    1      2       3    4
1    5      6       7    8

In [25]:
np.ones(shape=(10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
np.zeros(shape=(7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
np.arange(0,100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [29]:
np.random.randint(0,10, size=(7,2))

array([[1, 5],
       [8, 9],
       [1, 0],
       [1, 3],
       [6, 4],
       [1, 3],
       [2, 6]])

In [32]:
np.random.random(size=(4,6))

array([[0.40950171, 0.46272934, 0.56033264, 0.11466208, 0.6987599 ,
        0.81998782],
       [0.755228  , 0.81494439, 0.75974198, 0.03746472, 0.22000726,
        0.06329593],
       [0.78868629, 0.01290017, 0.58783658, 0.01276042, 0.82229407,
        0.69651377],
       [0.42576345, 0.81585553, 0.99919421, 0.93661117, 0.3706284 ,
        0.20262429]])

In [35]:
np.random.seed(40)
np.random.randint(0,10,size=(4,6))

array([[6, 7, 5, 8, 8, 2],
       [1, 7, 2, 3, 7, 3],
       [9, 0, 1, 5, 9, 8],
       [4, 4, 8, 6, 3, 3]])

In [36]:
rand_num = np.random.randint(1,7, size=(3,7))

In [37]:
rand_num

array([[2, 4, 6, 5, 6, 6, 3],
       [3, 3, 4, 5, 5, 2, 4],
       [4, 3, 3, 3, 5, 6, 1]])

In [44]:
pd.unique(rand_num.reshape(21,))

array([2, 4, 6, 5, 3, 1])

In [41]:
rand_num.ndim, rand_num.shape

(2, (3, 7))

In [46]:
rand_num

array([[2, 4, 6, 5, 6, 6, 3],
       [3, 3, 4, 5, 5, 2, 4],
       [4, 3, 3, 3, 5, 6, 1]])

In [54]:
rand_num[0, 0]

2

In [55]:
rand_num.argsort()

array([[0, 6, 1, 3, 2, 4, 5],
       [5, 0, 1, 2, 6, 3, 4],
       [6, 1, 2, 3, 0, 4, 5]], dtype=int64)

In [56]:
rand_num[:2]

array([[2, 4, 6, 5, 6, 6, 3],
       [3, 3, 4, 5, 5, 2, 4]])

In [57]:
rand_num[:2, :2]

array([[2, 4],
       [3, 3]])

In [63]:
arr = np.random.randint(0,10, size=(3,5))
one = np.ones(shape=(3,5))

In [64]:
arr.shape, one.shape

((3, 5), (3, 5))

In [65]:
arr+zero

array([[ 3., 10.,  8.,  4., 10.],
       [ 1.,  6.,  6.,  6.,  1.],
       [ 4.,  3.,  5., 10.,  8.]])

In [66]:
arr2 = np.random.randint(0,10, size = (5,3))

In [67]:
arr2

array([[6, 7, 7],
       [3, 4, 9],
       [4, 7, 2],
       [0, 8, 3],
       [8, 9, 5]])

In [69]:
arr2+one.reshape(5,3)

array([[ 7.,  8.,  8.],
       [ 4.,  5., 10.],
       [ 5.,  8.,  3.],
       [ 1.,  9.,  4.],
       [ 9., 10.,  6.]])

In [71]:
arr3 = np.ones(shape=(3,5))
one-arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
one*arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
arr3**2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [74]:
np.power(arr3,2)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
np.square(arr)

array([[ 4, 81, 49,  9, 81],
       [ 0, 25, 25, 25,  0],
       [ 9,  4, 16, 81, 49]])

In [77]:
np.mean(arr)

4.666666666666667

In [78]:
np.min(arr)

0

In [79]:
np.max(arr)

9

In [80]:
np.std(arr)

2.958978802822953

In [82]:
np.var(arr)

8.755555555555556

In [83]:
arr3.shape

(3, 5)

In [84]:
arr3.reshape(5,3,1)

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [85]:
arr3.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
arr2 = np.random.randint(0,10, size=(3,3))
arr3 = np.random.randint(0,10, size=(3,2))

In [87]:
arr2.dot(arr3)

array([[104,  46],
       [ 50,  22],
       [101,  45]])

In [88]:
arr2 = np.random.randint(0,10, size=(4,3))
arr3 = np.random.randint(0,10, size=(4,3))

In [90]:
arr2.dot(arr3.reshape(3,4))

array([[ 18,  91,  33, 141],
       [ 27, 112,  43, 147],
       [ 21, 106,  29, 113],
       [  0,  41,   2,  60]])

In [91]:
arr2.dot(arr3.T)

array([[ 45,  30, 101, 102],
       [ 35,  39,  92, 118],
       [  5,  69,  38, 132],
       [ 10,  42,  25,  71]])

In [92]:
arr2 > arr3

array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True],
       [False, False, False]])

In [93]:
arr2 >= arr3

array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True],
       [False, False, False]])

In [94]:
arr3>7

array([[False, False, False],
       [False, False, False],
       [False,  True, False],
       [ True, False,  True]])

In [95]:
arr2 == arr3

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [100]:
arr3.sort(kind='heapsort')

In [107]:
arr3.argmax()

8

In [102]:
arr3.argmin()

0

In [106]:
arr3.max()

9

In [108]:
arr3

array([[0, 0, 5],
       [0, 3, 6],
       [1, 3, 9],
       [4, 8, 9]])

In [109]:
arr3.argmax(axis=1)

array([2, 2, 2, 2], dtype=int64)

In [110]:
arr3.argmax(axis=0)

array([3, 3, 2], dtype=int64)

In [124]:
np.random.randn(3,5)

array([[-1.56460807,  0.28498131,  0.90930081, -0.05588715,  0.27093607],
       [-0.56355046,  0.84450328, -0.27413273, -0.62347637, -0.21277235],
       [-1.53509939, -0.81126502,  1.2108651 , -0.01403274, -0.1955312 ]])

In [126]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])